import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/register.css";  
import { Navbar } from "@/components/Navbar";
import { Breadcrumb } from "@/components/Breadcrumb";

const poppins = Poppins({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`} suppressHydrationWarning={true}>
        <Navbar />

        <Breadcrumb />
        <main>{children}</main>
      </body>
    </html>
  );
}
