import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { useEffect } from "react";
import {useAuthStore} from "@/store/auth";
import "@/styles/globals.css";
import { Navbar } from "@/components/Navbar"; 

import { Breadcrumb } from "@/components/Breadcrumb";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TrainIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Navbar/>
        <Breadcrumb/>
       <main>{children}</main>
      </body>
    </html>
  );
}
